name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [main, beta]
  pull_request:
    branches: [main, beta]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    strategy:
      matrix:
        node: [18, 20]

    name: Build Package (Node ${{ matrix.node }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Lint
        run: npm run lint && npm run lint:package && npm run format:check

      - name: Run tests against browser
        run: npm run test:browser

      - name: Run tests against Node
        run: npm run test:node
